const e = [
  {
    type: 0,
    description: "车-2",
    href: "resource/items/{{ theme }}/car_2.png",
    width: 4200,
    height: 1800,
    tag: "其他",
    direction: 3,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 1,
    description: "车-1",
    href: "resource/items/{{ theme }}/car_1.png",
    width: 1900,
    height: 4300,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 2,
    description: "中厨-1",
    href: "resource/items/{{ theme }}/kitchen_1.png",
    width: 3158,
    height: 1400,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 3,
    description: "8人餐桌",
    href: "resource/items/{{ theme }}/table_for_8.png",
    width: 3240,
    height: 1800,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 4,
    description: "衣柜-1",
    href: "resource/items/{{ theme }}/wardrobe_1.png",
    width: 1820,
    height: 600,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 5,
    description: "浴缸-2",
    href: "resource/items/{{ theme }}/bathtub_2.png",
    width: 1500,
    height: 694,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 6,
    description: "衣柜-3",
    href: "resource/items/{{ theme }}/wardrobe_3.png",
    width: 2830,
    height: 600,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 7,
    description: "植物-4",
    href: "resource/items/{{ theme }}/plant_4.png",
    width: 700,
    height: 628,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 8,
    description: "植物-1",
    href: "resource/items/{{ theme }}/plant_1.png",
    width: 700,
    height: 565,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 9,
    description: "植物-6",
    href: "resource/items/{{ theme }}/plant_6.png",
    width: 800,
    height: 758,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 10,
    description: "书桌-1",
    href: "resource/items/{{ theme }}/desk_1.png",
    width: 1200,
    height: 930,
    tag: "书房",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 11,
    description: "瓶艺-1",
    href: "resource/items/{{ theme }}/bottle_art_1.png",
    width: 530,
    height: 520,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 12,
    description: "衣柜-2",
    href: "resource/items/{{ theme }}/wardrobe_2.png",
    width: 2310,
    height: 600,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 13,
    description: "植物-2",
    href: "resource/items/{{ theme }}/plant_2.png",
    width: 600,
    height: 600,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 14,
    description: "西厨-1",
    href: "resource/items/{{ theme }}/western_kitchen_1.png",
    width: 2180,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 15,
    description: "西厨-2",
    href: "resource/items/{{ theme }}/western_kitchen_2.png",
    width: 1480,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 16,
    description: "浴缸-1",
    href: "resource/items/{{ theme }}/bathtub_1.png",
    width: 1500,
    height: 956,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 17,
    description: "植物-3",
    href: "resource/items/{{ theme }}/plant_3.png",
    width: 700,
    height: 639,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 18,
    description: "书桌-2",
    href: "resource/items/{{ theme }}/desk_2.png",
    width: 2200,
    height: 2470,
    tag: "书房",
    direction: 3,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 19,
    description: "吧台",
    href: "resource/items/{{ theme }}/bar_counter.png",
    width: 1800,
    height: 1130,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 20,
    description: "书柜-短",
    href: "resource/items/{{ theme }}/bookcase_short.png",
    width: 1460,
    height: 350,
    tag: "书房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 21,
    description: "鞋柜-长",
    href: "resource/items/{{ theme }}/shoe_cabinet_long.png",
    width: 2059,
    height: 550,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 22,
    description: "鞋柜-短",
    href: "resource/items/{{ theme }}/shoe_cabinet_short.png",
    width: 1308,
    height: 550,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 23,
    description: "中厨-2",
    href: "resource/items/{{ theme }}/kitchen_2.png",
    width: 2020,
    height: 650,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 24,
    description: "椅子",
    href: "resource/items/{{ theme }}/chair.png",
    width: 1050,
    height: 950,
    tag: "客厅",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 25,
    description: "秋千",
    href: "resource/items/{{ theme }}/swing.png",
    width: 1600,
    height: 1370,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 26,
    description: "茶几",
    href: "resource/items/{{ theme }}/tea_table.png",
    width: 1090,
    height: 800,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 27,
    description: "庭院",
    href: "resource/items/{{ theme }}/courtyard.png",
    width: 2100,
    height: 3020,
    tag: "其他",
    direction: 3,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 28,
    description: "躺椅",
    href: "resource/items/{{ theme }}/deck_chair.png",
    width: 900,
    height: 1850,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 29,
    description: "钢琴",
    href: "resource/items/{{ theme }}/piano.png",
    width: 1900,
    height: 2260,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 30,
    description: "音响",
    href: "resource/items/{{ theme }}/sound.png",
    width: 2500,
    height: 550,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 31,
    description: "马桶",
    href: "resource/items/{{ theme }}/flush_toilet.png",
    width: 450,
    height: 750,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 32,
    description: "植物-5",
    href: "resource/items/{{ theme }}/plant_5.png",
    width: 544,
    height: 600,
    tag: "装饰类",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 33,
    description: "书柜-长",
    href: "resource/items/{{ theme }}/bookcase_long.png",
    width: 2040,
    height: 350,
    tag: "书房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 34,
    description: "燃气灶-1",
    href: "resource/items/{{ theme }}/gas_stove_1.png",
    width: 820,
    height: 450,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 35,
    description: "洗脸池-单",
    href: "resource/items/{{ theme }}/wash_basin_single.png",
    width: 1150,
    height: 500,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 36,
    description: "洗手池-单",
    href: "resource/items/{{ theme }}/sink_single.png",
    width: 1200,
    height: 500,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 37,
    description: "双人床-4",
    href: "resource/items/{{ theme }}/double_4.png",
    width: 2743,
    height: 2e3,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 38,
    description: "电视柜-短",
    href: "resource/items/{{ theme }}/tv_cabinet_short.png",
    width: 1580,
    height: 350,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 39,
    description: "储物柜-1",
    href: "resource/items/{{ theme }}/locker_1.png",
    width: 1400,
    height: 600,
    tag: "储物间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 40,
    description: "双人床-3",
    href: "resource/items/{{ theme }}/double_3.png",
    width: 2791,
    height: 2300,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 41,
    description: "双人床-2",
    href: "resource/items/{{ theme }}/double_2.png",
    width: 2791,
    height: 2300,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 42,
    description: "洗手池-双",
    href: "resource/items/{{ theme }}/sink_double.png",
    width: 2777,
    height: 600,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 43,
    description: "洗脸池-双",
    href: "resource/items/{{ theme }}/wash_basin_double.png",
    width: 2550,
    height: 600,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 44,
    description: "双人床（无床头柜）-1",
    href: "resource/items/{{ theme }}/double_bed_without_bedside_table_1.png",
    width: 1914,
    height: 2e3,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 45,
    description: "电视柜-长",
    href: "resource/items/{{ theme }}/tv_cabinet_long.png",
    width: 2040,
    height: 350,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 46,
    description: "洽谈桌组合",
    href: "resource/items/{{ theme }}/negotiation_table_combination.png",
    width: 2830,
    height: 950,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 47,
    description: "哑铃架",
    href: "resource/items/{{ theme }}/dumbbell_rack.png",
    width: 900,
    height: 650,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 48,
    description: "沙发组合-1",
    href: "resource/items/{{ theme }}/sofa_combination_1.png",
    width: 4e3,
    height: 2792,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 49,
    description: "游泳池-2",
    href: "resource/items/{{ theme }}/swimming_pool_2.png",
    width: 7680,
    height: 3800,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 50,
    description: "美人榻",
    href: "resource/items/{{ theme }}/beauty_couch.png",
    width: 1600,
    height: 520,
    tag: "卧室",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 51,
    description: "单人床（无床头柜）",
    href: "resource/items/{{ theme }}/single_bed_without_bedside_table.png",
    width: 1200,
    height: 2120,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 52,
    description: "沙发组合-2",
    href: "resource/items/{{ theme }}/sofa_combination_2.png",
    width: 2e3,
    height: 2054,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 53,
    description: "跑步机",
    href: "resource/items/{{ theme }}/treadmill.png",
    width: 2120,
    height: 950,
    tag: "其他",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 54,
    description: "储物柜-3",
    href: "resource/items/{{ theme }}/lockers_3.png",
    width: 2400,
    height: 1360,
    tag: "储物间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 55,
    description: "洗菜池-1",
    href: "resource/items/{{ theme }}/vegetable_washing_pool_1.png",
    width: 760,
    height: 470,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 56,
    description: "组合沙发-4",
    href: "resource/items/{{ theme }}/combination_sofa_4.png",
    width: 1800,
    height: 1595,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 57,
    description: "台球桌",
    href: "resource/items/{{ theme }}/pool_table.png",
    width: 2540,
    height: 1400,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 58,
    description: "置物台-1",
    href: "resource/items/{{ theme }}/shelf_1.png",
    width: 1632,
    height: 560,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 59,
    description: "储物柜-2",
    href: "resource/items/{{ theme }}/locker_2.png",
    width: 2640,
    height: 600,
    tag: "储物间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 60,
    description: "户外桌椅",
    href: "resource/items/{{ theme }}/outdoor_tables_and_chairs.png",
    width: 3e3,
    height: 2800,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 61,
    description: "洗衣机-1",
    href: "resource/items/{{ theme }}/washing_machine_1.png",
    width: 850,
    height: 600,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 62,
    description: "双人床-1",
    href: "resource/items/{{ theme }}/double_1.png",
    width: 2851,
    height: 2200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 63,
    description: "六人餐桌",
    href: "resource/items/{{ theme }}/table_for_six.png",
    width: 2230,
    height: 1700,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 64,
    description: "洽谈沙发椅",
    href: "resource/items/{{ theme }}/sofa_chair.png",
    width: 1e3,
    height: 950,
    tag: "其他",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 65,
    description: "三人沙发",
    href: "resource/items/{{ theme }}/three_seat_sofa.png",
    width: 2670,
    height: 950,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 66,
    description: "会客桌",
    href: "resource/items/{{ theme }}/reception_table.png",
    width: 1800,
    height: 1800,
    tag: "其他",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 67,
    description: "健身机",
    href: "resource/items/{{ theme }}/fitness_machine.png",
    width: 2200,
    height: 800,
    tag: "其他",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 68,
    description: "沙发组合-3",
    href: "resource/items/{{ theme }}/sofa_combination_3.png",
    width: 2670,
    height: 2330,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 69,
    description: "双开冰箱",
    href: "resource/items/{{ theme }}/double_refrigerator.png",
    width: 720,
    height: 600,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 70,
    description: "车库工具箱",
    href: "resource/items/{{ theme }}/garage_toolbox.png",
    width: 1280,
    height: 500,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 71,
    description: "储物柜-4",
    href: "resource/items/{{ theme }}/locker_4.png",
    width: 2440,
    height: 2440,
    tag: "储物间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 72,
    description: "临时餐台",
    href: "resource/items/{{ theme }}/temporary_dining_table.png",
    width: 1e3,
    height: 1500,
    tag: "厨房",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 73,
    description: "置物台-2",
    href: "resource/items/{{ theme }}/shelf_2.png",
    width: 1590,
    height: 600,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 74,
    description: "四人餐桌",
    href: "resource/items/{{ theme }}/table_for_four.png",
    width: 1700,
    height: 1700,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 75,
    description: "洽谈桌",
    href: "resource/items/{{ theme }}/negotiating_table.png",
    width: 950,
    height: 950,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 76,
    description: "游泳池-1",
    href: "resource/items/{{ theme }}/swimming_pool_1.png",
    width: 4300,
    height: 5340,
    tag: "其他",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 77,
    description: "毛巾凳",
    href: "resource/items/{{ theme }}/towel_stool.png",
    width: 800,
    height: 500,
    tag: "卫生间",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 78,
    description: "电梯",
    href: "resource/items/{{ theme }}/lift.png",
    width: 2e3,
    height: 2e3,
    tag: "楼梯",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 79,
    description: "AC",
    href: "resource/items/{{ theme }}/ac.png",
    width: 850,
    height: 320,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 80,
    description: "二人餐桌",
    href: "resource/items/{{ theme }}/table_for_two.png",
    width: 780,
    height: 1500,
    tag: "客厅",
    direction: 1,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 81,
    description: "双人床（无床头柜）-2",
    href: "resource/items/{{ theme }}/double_bed_without_bedside_table_2.png",
    width: 1500,
    height: 2200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 82,
    description: "双人床（无床头柜）-3",
    href: "resource/items/{{ theme }}/double_bed_without_bedside_table_3.png",
    width: 1800,
    height: 2200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 83,
    description: "床头柜",
    href: "resource/items/{{ theme }}/bedstand.png",
    width: 500,
    height: 500,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 84,
    description: "单开门冰箱",
    href: "resource/items/{{ theme }}/refrigerator.png",
    width: 650,
    height: 670,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 85,
    description: "沙发组合-5",
    href: "resource/items/{{ theme }}/sofa_combination_5.png",
    width: 1598,
    height: 1418,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 86,
    description: "沙发组合-6",
    href: "resource/items/{{ theme }}/sofa_combination_6.png",
    width: 2680,
    height: 1790,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 87,
    description: "四人餐桌-1",
    href: "resource/items/{{ theme }}/table_for_four_1.png",
    width: 1600,
    height: 1700,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 88,
    description: "小单人沙发",
    href: "resource/items/{{ theme }}/chair_2.png",
    width: 460,
    height: 416,
    tag: "客厅",
    direction: 1,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 89,
    description: "小洗手池",
    href: "resource/items/{{ theme }}/sink_small.png",
    width: 600,
    height: 500,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 90,
    description: "小厨",
    href: "resource/items/{{ theme }}/kitchen_small.png",
    width: 740,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 91,
    description: "小衣柜",
    href: "resource/items/{{ theme }}/wardrobe_small.png",
    width: 910,
    height: 600,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 92,
    description: "淋浴房",
    href: "resource/items/{{ theme }}/shower.png",
    width: 650,
    height: 670,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 93,
    description: "鞋柜-1",
    href: "resource/items/{{ theme }}/shoe_cabinet_1.png",
    width: 900,
    height: 400,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 94,
    description: "鞋柜-2",
    href: "resource/items/{{ theme }}/shoe_cabinet_2.png",
    width: 1500,
    height: 400,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 95,
    description: "鞋柜-3",
    href: "resource/items/{{ theme }}/shoe_cabinet_3.png",
    width: 2e3,
    height: 400,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 96,
    description: "电视柜-1",
    href: "resource/items/{{ theme }}/tv_cabinet_1.png",
    width: 1500,
    height: 350,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 97,
    description: "电视柜-2",
    href: "resource/items/{{ theme }}/tv_cabinet_2.png",
    width: 2040,
    height: 350,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 98,
    description: "电视柜-3",
    href: "resource/items/{{ theme }}/tv_cabinet_3.png",
    width: 3e3,
    height: 350,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 99,
    description: "餐边柜-1",
    href: "resource/items/{{ theme }}/sideboard_1.png",
    width: 900,
    height: 550,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 100,
    description: "餐边柜-2",
    href: "resource/items/{{ theme }}/sideboard_2.png",
    width: 1500,
    height: 550,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 101,
    description: "餐边柜-3",
    href: "resource/items/{{ theme }}/sideboard_3.png",
    width: 2e3,
    height: 550,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 102,
    description: "燃气灶-2",
    href: "resource/items/{{ theme }}/gas_stove_2.png",
    width: 900,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 103,
    description: "洗菜池-2",
    href: "resource/items/{{ theme }}/vegetable_washing_pool_2.png",
    width: 900,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 104,
    description: "橱柜-1",
    href: "resource/items/{{ theme }}/kitchen_cabinet_1.png",
    width: 550,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 105,
    description: "橱柜-2",
    href: "resource/items/{{ theme }}/kitchen_cabinet_2.png",
    width: 900,
    height: 550,
    tag: "厨房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 106,
    description: "花洒",
    href: "resource/items/{{ theme }}/shower_head.png",
    width: 260,
    height: 200,
    tag: "卫生间",
    direction: 1,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 107,
    description: "淋浴屏",
    href: "resource/items/{{ theme }}/shower_panel.png",
    width: 1500,
    height: 100,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 108,
    description: "洗衣机-2",
    href: "resource/items/{{ theme }}/washing_machine_2.png",
    width: 600,
    height: 500,
    tag: "卫生间",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 109,
    description: "双人床-5",
    href: "resource/items/{{ theme }}/double_5.png",
    width: 1500,
    height: 2e3,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 110,
    description: "双人床-6",
    href: "resource/items/{{ theme }}/double_6.png",
    width: 1800,
    height: 2e3,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 111,
    description: "双人床-7",
    href: "resource/items/{{ theme }}/double_7.png",
    width: 2e3,
    height: 2200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 112,
    description: "双人床-8",
    href: "resource/items/{{ theme }}/double_8.png",
    width: 2300,
    height: 2200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 113,
    description: "梳妆台",
    href: "resource/items/{{ theme }}/dressing_table.png",
    width: 1200,
    height: 900,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 114,
    description: "儿童床-1",
    href: "resource/items/{{ theme }}/children_bed_1.png",
    width: 1400,
    height: 2e3,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 115,
    description: "儿童床-2",
    href: "resource/items/{{ theme }}/children_bed_2.png",
    width: 1700,
    height: 2e3,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 116,
    description: "儿童床-3",
    href: "resource/items/{{ theme }}/children_bed_3.png",
    width: 2e3,
    height: 2200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 117,
    description: "儿童书桌-1",
    href: "resource/items/{{ theme }}/children_desk_1.png",
    width: 1e3,
    height: 800,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 118,
    description: "儿童书桌-2",
    href: "resource/items/{{ theme }}/children_desk_2.png",
    width: 1200,
    height: 800,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 119,
    description: "儿童书桌-3",
    href: "resource/items/{{ theme }}/children_desk_3.png",
    width: 1500,
    height: 800,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 120,
    description: "儿童活动区域-1",
    href: "resource/items/{{ theme }}/children_carpet_1.png",
    width: 600,
    height: 600,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 121,
    description: "儿童活动区域-2",
    href: "resource/items/{{ theme }}/children_carpet_2.png",
    width: 1200,
    height: 1200,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 122,
    description: "儿童活动区域-3",
    href: "resource/items/{{ theme }}/children_carpet_3.png",
    width: 1800,
    height: 1800,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 123,
    description: "茶榻组合-1",
    href: "resource/items/{{ theme }}/tea_table_combination_1.png",
    width: 2e3,
    height: 1400,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 124,
    description: "茶榻组合-2",
    href: "resource/items/{{ theme }}/tea_table_combination_2.png",
    width: 2500,
    height: 1400,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 125,
    description: "茶榻组合-3",
    href: "resource/items/{{ theme }}/tea_table_combination_3.png",
    width: 3e3,
    height: 1800,
    tag: "其他",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 126,
    description: "儿童衣柜-1",
    href: "resource/items/{{ theme }}/children_wardrobe_1.png",
    width: 900,
    height: 500,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 127,
    description: "儿童衣柜-2",
    href: "resource/items/{{ theme }}/children_wardrobe_2.png",
    width: 1200,
    height: 500,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 128,
    description: "儿童衣柜-3",
    href: "resource/items/{{ theme }}/children_wardrobe_3.png",
    width: 1500,
    height: 500,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 129,
    description: "儿童书柜-1",
    href: "resource/items/{{ theme }}/children_bookcase_1.png",
    width: 800,
    height: 450,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 130,
    description: "儿童书柜-2",
    href: "resource/items/{{ theme }}/children_bookcase_2.png",
    width: 1200,
    height: 450,
    tag: "卧室",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 131,
    description: "折行双跑楼梯",
    href: "resource/items/{{ theme }}/folding_double_running_stairs.png",
    width: 3e3,
    height: 3e3,
    tag: "楼梯",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 132,
    description: "平行双跑楼梯",
    href: "resource/items/{{ theme }}/parallel_double_running_stairs.png",
    width: 2500,
    height: 3600,
    tag: "楼梯",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 133,
    description: "折行三跑楼梯",
    href: "resource/items/{{ theme }}/folding_treble_running_stairs.png",
    width: 4300,
    height: 2700,
    tag: "楼梯",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !0
  },
  {
    type: 134,
    description: "手枪",
    href: "resource/items/{{ theme }}/pistol.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 135,
    description: "血迹",
    href: "resource/items/{{ theme }}/bloodstain.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 2,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 136,
    description: "手印",
    href: "resource/items/{{ theme }}/handprint.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 137,
    description: "足迹",
    href: "resource/items/{{ theme }}/footprint.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 138,
    description: "车轮轨迹",
    href: "resource/items/{{ theme }}/wheelprint.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 139,
    description: "弹头",
    href: "resource/items/{{ theme }}/bullet.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 140,
    description: "弹壳",
    href: "resource/items/{{ theme }}/shell.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 1,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 141,
    description: "尸体",
    href: "resource/items/{{ theme }}/corpse.png",
    width: 1500,
    height: 1500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["legacy", "realsee"],
    label: !1
  },
  {
    type: 142,
    description: "空气净化器",
    href: "resource/items/{{ theme }}/airscrubber.png",
    width: 580,
    height: 380,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 143,
    description: "吹风机",
    href: "resource/items/{{ theme }}/airblower.png",
    width: 640,
    height: 600,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 144,
    description: "除湿器",
    href: "resource/items/{{ theme }}/dehumidifier.png",
    width: 480,
    height: 430,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 145,
    description: "冰柜",
    href: "resource/items/{{ theme }}/freezer.png",
    width: 800,
    height: 460,
    tag: "厨房",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 146,
    description: "架子",
    href: "resource/items/{{ theme }}/shelf.png",
    width: 1e3,
    height: 380,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 147,
    description: "杂物",
    href: "resource/items/{{ theme }}/sundries.png",
    width: 800,
    height: 800,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 148,
    description: "L型沙发",
    href: "resource/items/{{ theme }}/L_sofa.png",
    width: 3500,
    height: 1800,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 149,
    description: "书桌3",
    href: "resource/items/{{ theme }}/desk_3.png",
    width: 1200,
    height: 680,
    tag: "书房",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 150,
    description: "会议桌-1",
    href: "resource/items/{{ theme }}/conference_table_1.png",
    width: 1600,
    height: 1100,
    tag: "客厅",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 151,
    description: "衣架",
    href: "resource/items/{{ theme }}/coat_hanger.png",
    width: 1200,
    height: 400,
    tag: "卧室",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 152,
    description: "上下铺",
    href: "resource/items/{{ theme }}/bunk_beds.png",
    width: 2e3,
    height: 1040,
    tag: "卧室",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 153,
    description: "蹲坑",
    href: "resource/items/{{ theme }}/squatting.png",
    width: 600,
    height: 480,
    tag: "卫生间",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 154,
    description: "男尸",
    href: "resource/items/{{ theme }}/male_corpse.png",
    width: 1600,
    height: 800,
    tag: "物证痕迹",
    direction: 1,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 155,
    description: "女尸",
    href: "resource/items/{{ theme }}/female_corpse.png",
    width: 1500,
    height: 800,
    tag: "物证痕迹",
    direction: 1,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 156,
    description: "擦蹭状血迹",
    href: "resource/items/{{ theme }}/rub-like-bookd-stains.png",
    width: 1200,
    height: 800,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 157,
    description: "擦拭物",
    href: "resource/items/{{ theme }}/wipes.png",
    width: 300,
    height: 60,
    tag: "物证痕迹",
    direction: 3,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 158,
    description: "纸团",
    href: "resource/items/{{ theme }}/paper_ball.png",
    width: 400,
    height: 400,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 159,
    description: "未整理的被子",
    href: "resource/items/{{ theme }}/unarranged_quilts.png",
    width: 800,
    height: 500,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 160,
    description: "手机",
    href: "resource/items/{{ theme }}/mobile_phone.png",
    width: 400,
    height: 280,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 161,
    description: "菜刀",
    href: "resource/items/{{ theme }}/kitchen_knife.png",
    width: 500,
    height: 220,
    tag: "物证痕迹",
    direction: 3,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 162,
    description: "矩形",
    href: "resource/items/{{ theme }}/rectangle.png",
    width: 900,
    height: 600,
    tag: "自定义",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0,
    svgWidth: 90,
    svgHeight: 60,
    svg: '<rect x=".75" y=".75" width="88.5" height="58.5" rx="4" fill="#FFF" stroke="#3D404E" fill-rule="evenodd" vector-effect="non-scaling-stroke"/>'
  },
  {
    type: 163,
    description: "圆形",
    href: "resource/items/{{ theme }}/circle.png",
    width: 600,
    height: 600,
    tag: "自定义",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 164,
    description: "三角形",
    href: "resource/items/{{ theme }}/triangle.png",
    width: 600,
    height: 600,
    tag: "自定义",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 165,
    description: "五角星形",
    href: "resource/items/{{ theme }}/five_pointedstar.png",
    width: 800,
    height: 800,
    tag: "自定义",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 166,
    description: "会议桌-2",
    href: "resource/items/{{ theme }}/conference_table_2.png",
    width: 2800,
    height: 1800,
    tag: "客厅",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 167,
    description: "餐椅",
    href: "resource/items/{{ theme }}/dining_chair.png",
    width: 500,
    height: 580,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 168,
    description: "转椅-1",
    href: "resource/items/{{ theme }}/rotating_chair_1.png",
    width: 500,
    height: 580,
    tag: "书房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 169,
    description: "转椅-2",
    href: "resource/items/{{ theme }}/rotating_chair_2.png",
    width: 640,
    height: 640,
    tag: "书房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 170,
    description: "长方形茶几",
    href: "resource/items/{{ theme }}/rectangular_coffee_table.png",
    width: 1090,
    height: 800,
    tag: "客厅",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 171,
    description: "抽油烟机",
    href: "resource/items/{{ theme }}/smoke_lampblack_machine.png",
    width: 1200,
    height: 800,
    tag: "厨房",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 172,
    description: "电话机",
    href: "resource/items/{{ theme }}/telephone.png",
    width: 500,
    height: 500,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 173,
    description: "对讲机",
    href: "resource/items/{{ theme }}/walkie_talkie.png",
    width: 240,
    height: 540,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 174,
    description: "花盆",
    href: "resource/items/{{ theme }}/flower_pot.png",
    width: 500,
    height: 500,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 175,
    description: "剪刀",
    href: "resource/items/{{ theme }}/scissors.png",
    width: 500,
    height: 460,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 176,
    description: "角柜",
    href: "resource/items/{{ theme }}/corner_cabinet.png",
    width: 1e3,
    height: 1e3,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 177,
    description: "口杯",
    href: "resource/items/{{ theme }}/mouth_cup.png",
    width: 500,
    height: 400,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 178,
    description: "盘子",
    href: "resource/items/{{ theme }}/plate.png",
    width: 500,
    height: 500,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 179,
    description: "勺子",
    href: "resource/items/{{ theme }}/spoon.png",
    width: 600,
    height: 180,
    tag: "日常用品",
    direction: 1,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 180,
    description: "手提包",
    href: "resource/items/{{ theme }}/handbag.png",
    width: 500,
    height: 500,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 181,
    description: "双人沙发",
    href: "resource/items/{{ theme }}/double_sofa.png",
    width: 1600,
    height: 850,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 182,
    description: "藤椅",
    href: "resource/items/{{ theme }}/cane_chair.png",
    width: 640,
    height: 640,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 183,
    description: "拖把",
    href: "resource/items/{{ theme }}/mop.png",
    width: 490,
    height: 1e3,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 184,
    description: "卫生纸",
    href: "resource/items/{{ theme }}/toilet_paper.png",
    width: 280,
    height: 300,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 185,
    description: "烟盒",
    href: "resource/items/{{ theme }}/cigarette_case.png",
    width: 220,
    height: 300,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 186,
    description: "烟头",
    href: "resource/items/{{ theme }}/cigarette_butt.png",
    width: 280,
    height: 220,
    tag: "日常用品",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 187,
    description: "鱼缸",
    href: "resource/items/{{ theme }}/fish_tank.png",
    width: 1e3,
    height: 500,
    tag: "客厅",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 188,
    description: "笔记本电脑",
    href: "resource/items/{{ theme }}/notebook_computer.png",
    width: 500,
    height: 500,
    tag: "日常用品",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 189,
    description: "微波炉",
    href: "resource/items/{{ theme }}/microwave_oven.png",
    width: 600,
    height: 400,
    tag: "厨房",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 190,
    description: "断口",
    href: "resource/items/{{ theme }}/fracture.png",
    width: 1200,
    height: 300,
    tag: "其他",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !0
  },
  {
    type: 191,
    description: "遗物堆",
    href: "resource/items/{{ theme }}/relic_pile.png",
    width: 800,
    height: 800,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 192,
    description: "衣物",
    href: "resource/items/{{ theme }}/clothing.png",
    width: 830,
    height: 810,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 193,
    description: "浴巾",
    href: "resource/items/{{ theme }}/bath_towel.png",
    width: 420,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 194,
    description: "水渍",
    href: "resource/items/{{ theme }}/water_stains.png",
    width: 1070,
    height: 600,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 195,
    description: "螺丝刀",
    href: "resource/items/{{ theme }}/bolt_driver.png",
    width: 300,
    height: 300,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 196,
    description: "凉鞋",
    href: "resource/items/{{ theme }}/sandals.png",
    width: 430,
    height: 460,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 197,
    description: "水果刀",
    href: "resource/items/{{ theme }}/fruit_knife.png",
    width: 300,
    height: 260,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 198,
    description: "匕首",
    href: "resource/items/{{ theme }}/dragger.png",
    width: 400,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 199,
    description: "玻璃弹孔",
    href: "resource/items/{{ theme }}/glass_bullet_hole.png",
    width: 1160,
    height: 1e3,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 200,
    description: "电视",
    href: "resource/items/{{ theme }}/tv.png",
    width: 1120,
    height: 160,
    tag: "客厅",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 201,
    description: "单向楼梯",
    href: "resource/items/{{ theme }}/stairs.png",
    width: 1400,
    height: 3600,
    tag: "楼梯",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 202,
    description: "电脑",
    href: "resource/items/{{ theme }}/computer.png",
    width: 700,
    height: 120,
    tag: "书房",
    direction: 2,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 203,
    description: "工具",
    href: "resource/items/{{ theme }}/tool.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 204,
    description: "特殊",
    href: "resource/items/{{ theme }}/special.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 205,
    description: "生物",
    href: "resource/items/{{ theme }}/biology.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 206,
    description: "毒化",
    href: "resource/items/{{ theme }}/poison.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 207,
    description: "理化",
    href: "resource/items/{{ theme }}/physics&chemistry.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 208,
    description: "文检",
    href: "resource/items/{{ theme }}/document.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 209,
    description: "电子",
    href: "resource/items/{{ theme }}/electronic.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 210,
    description: "人像",
    href: "resource/items/{{ theme }}/portrait.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 211,
    description: "提取物品",
    href: "resource/items/{{ theme }}/extract_items.png",
    width: 500,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 212,
    description: "左脚足迹",
    href: "resource/items/{{ theme }}/footprint_l.png",
    width: 220,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 213,
    description: "右脚足迹",
    href: "resource/items/{{ theme }}/footprint_r.png",
    width: 220,
    height: 500,
    tag: "物证痕迹",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 214,
    description: "电动车",
    href: "resource/items/{{ theme }}/electric_car.png",
    width: 480,
    height: 1320,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 215,
    description: "自行车",
    href: "resource/items/{{ theme }}/bike.png",
    width: 380,
    height: 1480,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 216,
    description: "摩托车",
    href: "resource/items/{{ theme }}/motorcycle.png",
    width: 500,
    height: 1780,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 217,
    description: "越野车",
    href: "resource/items/{{ theme }}/off_road_vehicle.png",
    width: 1700,
    height: 4360,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 218,
    description: "卡车",
    href: "resource/items/{{ theme }}/truck.png",
    width: 1880,
    height: 6800,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 219,
    description: "客车",
    href: "resource/items/{{ theme }}/bus.png",
    width: 3160,
    height: 8e3,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 220,
    description: "叉车",
    href: "resource/items/{{ theme }}/forklift.png",
    width: 940,
    height: 2720,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  },
  {
    type: 221,
    description: "拖拉机",
    href: "resource/items/{{ theme }}/tractor.png",
    width: 1740,
    height: 3060,
    tag: "交通工具",
    direction: 0,
    keywords: ["default"],
    themes: ["realsee"],
    label: !1
  }
];
export {
  e as default
};
