name: Build and Deploy Example

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install and Build
        run: |
          npm install -g pnpm
          pnpm i
          pnpm run build

      - name: Setup online folder and copy build artifacts
        run: |
          mkdir online
          cp -r open-works online/open-works
          cp -r dist/* online/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.LCJ_GITHUB_TOKEN }}
          publish_dir: ./online
